### PR TITLE
fix installation

### PR DESCRIPTION
**Pull request by a-x-**
... also, please or contribute it back into original repo or ask to transfer original repo to you.

semver based matcher is totally must have!

### CODE REVIEW

**Comment by a-x-** [comment]
or all of comunity should change original package to your
https://github.com/typicode/husky/pull/451

**Comment by a-x-** [comment]
**UPD**

looks like please-upgrade added semver, but had not updated his readme
typicode/please-upgrade-node#9

can you archive repo like so?

**Comment by aladdin-add** [comment]
thanks for the info! I'll deprecate the fork.

**Comment by a-x-** [comment]
I checked semver-compare library, that please-upgrade-node uses. It's incorrect.
e.g. I have `engines.node` = `9.x.x || 11.x.x` and node -v = 10.15.1

semver-compare will work only with 9.x.x and will be compare `10.15.1 >= 9.x.x`

**Comment by a-x-** [comment]
I think we used to fix original repo.
It must work with any correct semver comparation expression that npm allows:
afaik, e.g., `>= 9.x.x`, `9.x.x`, `9.x.x || 11.x.x`, and etc.

**Comment by aladdin-add** [comment]
it seems by design(as in its readme):
> Important: >= is the only operator supported by please-upgrade-node (e.g. >=6, >=6.0, >=6.0.0).

it would be great if it could be fixed in the original repo, but it seems no longer maintained :-(

**Comment by a-x-** [comment]
I create PR to their another active repo

https://github.com/typicode/husky/pull/454

**Pull request merged**
